import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/globalComponent/Header";
import Footer from "@/globalComponent/Footer";
import { PopupProvider } from "@/globalComponent/PopupContext";
import PopupForm from "@/globalComponent/PopupForm";

// Load fonts from Google Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap everything with the PopupProvider to manage popup state globally */}
        <PopupProvider>
          {/* Header is globally available */}
          <Header />
<PopupForm />
          {/* Injected page content */}
          {children}

          {/* Footer is globally available */}
          <Footer />
        </PopupProvider>
      </body>
    </html>
  );
}
